//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF简单客户端.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/StrName", ReplyAction="http://tempuri.org/IService2/StrNameResponse")]
        string StrName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/StrName", ReplyAction="http://tempuri.org/IService2/StrNameResponse")]
        System.Threading.Tasks.Task<string> StrNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCount", ReplyAction="http://tempuri.org/IService1/GetCountResponse")]
        int GetCount(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCount", ReplyAction="http://tempuri.org/IService1/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Str", ReplyAction="http://tempuri.org/IService1/StrResponse")]
        string Str();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Str", ReplyAction="http://tempuri.org/IService1/StrResponse")]
        System.Threading.Tasks.Task<string> StrAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF简单客户端.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF简单客户端.ServiceReference1.IService1>, WCF简单客户端.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StrName() {
            return base.Channel.StrName();
        }
        
        public System.Threading.Tasks.Task<string> StrNameAsync() {
            return base.Channel.StrNameAsync();
        }
        
        public int GetCount(int x, int y) {
            return base.Channel.GetCount(x, y);
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync(int x, int y) {
            return base.Channel.GetCountAsync(x, y);
        }
        
        public string Str() {
            return base.Channel.Str();
        }
        
        public System.Threading.Tasks.Task<string> StrAsync() {
            return base.Channel.StrAsync();
        }
    }
}
