//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class testEF
    {
        public int ID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<System.DateTime> NowTime { get; set; }
        public Nullable<int> SUM { get; set; }
    }
}
